package rekisteri.test;
// Generated by ComTest BEGIN
import rekisteri.*;
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import java.util.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.22 16:21:57 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HuomiotTest {



  // Generated by ComTest BEGIN
  /** 
   * testKorvaaLisaa47 
   * @throws SailoException when error
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testKorvaaLisaa47() throws SailoException,CloneNotSupportedException {    // Huomiot: 47
    Huomiot huomiot = new Huomiot(); 
    Huomio huom1 = new Huomio(), huom2 = new Huomio(); 
    huom1.rekisterointi(); huom2.rekisterointi(); 
    assertEquals("From: Huomiot line: 53", 0, huomiot.getLkm()); 
    huomiot.korvaaLisaa(huom1); assertEquals("From: Huomiot line: 54", 1, huomiot.getLkm()); 
    huomiot.korvaaLisaa(huom1); assertEquals("From: Huomiot line: 55", 2, huomiot.getLkm()); 
    Huomio huom3 = huom1.clone(); 
    huom3.aseta(2,"kkk"); 
    Iterator<Huomio> i2=huomiot.iterator(); 
    assertEquals("From: Huomiot line: 59", huom1, i2.next()); 
    huomiot.korvaaLisaa(huom3); assertEquals("From: Huomiot line: 60", 2, huomiot.getLkm()); 
    i2=huomiot.iterator(); 
    Huomio h = i2.next(); 
    assertEquals("From: Huomiot line: 63", huom3, h); 
    assertEquals("From: Huomiot line: 64", true, h == huom3); 
    assertEquals("From: Huomiot line: 65", false, h == huom1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedosto112 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedosto112() throws SailoException {    // Huomiot: 112
    Huomiot huomioita = new Huomiot(); 
    Huomio sataa2 = new Huomio(); sataa2.testiHuomio(2); 
    Huomio sataa1 = new Huomio(); sataa1.testiHuomio(1); 
    Huomio sataa21 = new Huomio(); sataa21.testiHuomio(2); 
    Huomio sataa12 = new Huomio(); sataa12.testiHuomio(1); 
    Huomio sataa22 = new Huomio(); sataa22.testiHuomio(2); 
    String tiedostoNimi = "testirekisteri"; 
    File ftied = new File(tiedostoNimi+".dat"); 
    ftied.delete(); 
    try {
    huomioita.lueTiedosto(tiedostoNimi); 
    fail("Huomiot: 124 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    huomioita.lisaa(sataa2); 
    huomioita.lisaa(sataa1); 
    huomioita.lisaa(sataa21); 
    huomioita.lisaa(sataa12); 
    huomioita.lisaa(sataa22); 
    huomioita.tallennus(); 
    huomioita = new Huomiot(); 
    huomioita.lueTiedosto(tiedostoNimi); 
    Iterator<Huomio> i = huomioita.iterator(); 
    assertEquals("From: Huomiot line: 134", sataa2.toString(), i.next().toString()); 
    assertEquals("From: Huomiot line: 135", sataa1.toString(), i.next().toString()); 
    assertEquals("From: Huomiot line: 136", sataa21.toString(), i.next().toString()); 
    assertEquals("From: Huomiot line: 137", sataa12.toString(), i.next().toString()); 
    assertEquals("From: Huomiot line: 138", sataa22.toString(), i.next().toString()); 
    assertEquals("From: Huomiot line: 139", false, i.hasNext()); 
    huomioita.lisaa(sataa22); 
    huomioita.tallennus(); 
    assertEquals("From: Huomiot line: 142", true, ftied.delete()); 
    File fback = new File(tiedostoNimi+".bak"); 
    assertEquals("From: Huomiot line: 144", true, fback.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator246 */
  @Test
  public void testIterator246() {    // Huomiot: 246
    Huomiot huomioita = new Huomiot(); 
    Huomio sataa1 = new Huomio(1); huomioita.lisaa(sataa1); 
    Huomio sataa2 = new Huomio(2); huomioita.lisaa(sataa2); 
    Huomio sataa12 = new Huomio(1); huomioita.lisaa(sataa12); 
    Huomio sataa21 = new Huomio(2); huomioita.lisaa(sataa21); 
    Huomio sataa13 = new Huomio(1); huomioita.lisaa(sataa13); 
    Iterator<Huomio> ite = huomioita.iterator(); 
    assertEquals("From: Huomiot line: 259", sataa1, ite.next()); 
    assertEquals("From: Huomiot line: 260", sataa2, ite.next()); 
    assertEquals("From: Huomiot line: 261", sataa12, ite.next()); 
    assertEquals("From: Huomiot line: 262", sataa21, ite.next()); 
    assertEquals("From: Huomiot line: 263", sataa13, ite.next()); 
    try {
    assertEquals("From: Huomiot line: 264", sataa1, ite.next()); 
    fail("Huomiot: 264 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int htunnus[] = { 1,2,1,2,1} ; 
    for (Huomio h : huomioita) {
    assertEquals("From: Huomiot line: 270", htunnus[n], h.getPaivaId()); n++; 
    }
    assertEquals("From: Huomiot line: 273", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaHuomio288 */
  @Test
  public void testAnnaHuomio288() {    // Huomiot: 288
    Huomiot huomioita = new Huomiot(); 
    Huomio sataa1 = new Huomio(1); huomioita.lisaa(sataa1); 
    Huomio sataa2 = new Huomio(2); huomioita.lisaa(sataa2); 
    Huomio sataa12 = new Huomio(1); huomioita.lisaa(sataa12); 
    Huomio sataa21 = new Huomio(2); huomioita.lisaa(sataa21); 
    Huomio sataa13 = new Huomio(1); huomioita.lisaa(sataa13); 
    Huomio sataa41 = new Huomio(4); huomioita.lisaa(sataa41); 
    List <Huomio> test; 
    test = huomioita.annaHuomio(10); 
    assertEquals("From: Huomiot line: 301", 0, test.size()); 
    test = huomioita.annaHuomio(1); 
    assertEquals("From: Huomiot line: 303", 3, test.size()); 
    assertEquals("From: Huomiot line: 304", true, test.get(0) == sataa1); 
    assertEquals("From: Huomiot line: 305", true, test.get(1) == sataa12); 
    test = huomioita.annaHuomio(4); 
    assertEquals("From: Huomiot line: 307", 1, test.size()); 
    assertEquals("From: Huomiot line: 308", true, test.get(0) == sataa41); 
  } // Generated by ComTest END
}