package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.22 17:32:17 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HuomioTest {



  // Generated by ComTest BEGIN
  /** testRekisterointi44 */
  @Test
  public void testRekisterointi44() {    // Huomio: 44
    Huomio huom1 = new Huomio(); 
    assertEquals("From: Huomio line: 46", 0, huom1.getHuomioId()); 
    huom1.rekisterointi(); 
    Huomio huom2 = new Huomio(); 
    huom2.rekisterointi(); 
    int n1 = huom1.getHuomioId(); 
    int n2 = huom2.getHuomioId(); 
    assertEquals("From: Huomio line: 52", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString128 */
  @Test
  public void testToString128() {    // Huomio: 128
    Huomio huomio = new Huomio(); 
    huomio.parse("   1   |  5  |   Sataa paljon  | 12:00"); 
    assertEquals("From: Huomio line: 131", "1|5|Sataa paljon|12:00", huomio.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse151 */
  @Test
  public void testParse151() {    // Huomio: 151
    Huomio huomio = new Huomio(); 
    huomio.parse("   1   |  5  |   Sataa paljon  | 12:00"); 
    assertEquals("From: Huomio line: 154", 5, huomio.getPaivaId()); 
    assertEquals("From: Huomio line: 155", "1|5|Sataa paljon|12:00", huomio.toString()); 
    huomio.rekisterointi(); 
    int n = huomio.getHuomioId(); 
    huomio.parse(""+(n+5)); 
    huomio.rekisterointi(); 
    assertEquals("From: Huomio line: 161", n+5+1, huomio.getHuomioId()); 
    assertEquals("From: Huomio line: 162", "" + (n+5+1) + "|5||12:00", huomio.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta235 */
  @Test
  public void testAseta235() {    // Huomio: 235
    Huomio huom = new Huomio(); 
    assertEquals("From: Huomio line: 237", "Ei ole sopiva kellonaika.", huom.aseta(3, "peruna")); 
    assertEquals("From: Huomio line: 238", null, huom.aseta(3, "11:00")); 
    assertEquals("From: Huomio line: 239", "Väärä indeksi", huom.aseta(4, "peruna")); 
  } // Generated by ComTest END
}