package rekisteri.test;
// Generated by ComTest BEGIN
import rekisteri.*;
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import java.util.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.22 17:37:32 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HuomiotTest {



  // Generated by ComTest BEGIN
  /** 
   * testKorvaaLisaa47 
   * @throws SailoException when error
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testKorvaaLisaa47() throws SailoException,CloneNotSupportedException {    // Huomiot: 47
    Huomiot huomiot = new Huomiot(); 
    Huomio huom1 = new Huomio(), huom2 = new Huomio(); 
    huom1.rekisterointi(); huom2.rekisterointi(); 
    assertEquals("From: Huomiot line: 53", 0, huomiot.getLkm()); 
    huomiot.korvaaLisaa(huom1); assertEquals("From: Huomiot line: 54", 1, huomiot.getLkm()); 
    huomiot.korvaaLisaa(huom1); assertEquals("From: Huomiot line: 55", 1, huomiot.getLkm()); 
    Huomio huom3 = huom1.clone(); 
    huom3.aseta(2,"kkk"); 
    Iterator<Huomio> i2=huomiot.iterator(); 
    assertEquals("From: Huomiot line: 59", huom1, i2.next()); 
    huomiot.korvaaLisaa(huom3); assertEquals("From: Huomiot line: 60", 1, huomiot.getLkm()); 
    i2=huomiot.iterator(); 
    Huomio h = i2.next(); 
    assertEquals("From: Huomiot line: 63", huom3, h); 
    assertEquals("From: Huomiot line: 64", true, h == huom3); 
    assertEquals("From: Huomiot line: 65", false, h == huom1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista84 
   * @throws SailoException when error
   */
  @Test
  public void testPoista84() throws SailoException {    // Huomiot: 84
    Huomiot huomiot1 = new Huomiot(); 
    Huomio sataa21 = new Huomio(); sataa21.testiHuomio(2); 
    Huomio sataa11 = new Huomio(); sataa11.testiHuomio(1); 
    Huomio sataa22 = new Huomio(); sataa22.testiHuomio(2); 
    Huomio sataa12 = new Huomio(); sataa12.testiHuomio(1); 
    Huomio sataa23 = new Huomio(); sataa23.testiHuomio(2); 
    huomiot1.lisaa(sataa21); 
    huomiot1.lisaa(sataa11); 
    huomiot1.lisaa(sataa22); 
    huomiot1.lisaa(sataa12); 
    assertEquals("From: Huomiot line: 97", true, huomiot1.poista(sataa23)); assertEquals("From: Huomiot line: 97", 3, huomiot1.getLkm()); 
    List<Huomio> huo = huomiot1.annaHuomio(1); 
    assertEquals("From: Huomiot line: 99", 2, huo.size()); 
    assertEquals("From: Huomiot line: 100", sataa12, huo.get(0)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoistaPaivanHuomiot113 */
  @Test
  public void testPoistaPaivanHuomiot113() {    // Huomiot: 113
    Huomiot huomiot1 = new Huomiot(); 
    Huomio sataa21 = new Huomio(); sataa21.testiHuomio(2); 
    Huomio sataa11 = new Huomio(); sataa11.testiHuomio(1); 
    Huomio sataa22 = new Huomio(); sataa22.testiHuomio(2); 
    Huomio sataa12 = new Huomio(); sataa12.testiHuomio(1); 
    Huomio sataa23 = new Huomio(); sataa23.testiHuomio(2); 
    huomiot1.lisaa(sataa21); 
    huomiot1.lisaa(sataa11); 
    huomiot1.lisaa(sataa22); 
    huomiot1.lisaa(sataa12); 
    huomiot1.lisaa(sataa23); 
    assertEquals("From: Huomiot line: 125", 3, huomiot1.poistaPaivanHuomiot(2)); assertEquals("From: Huomiot line: 125", 2, huomiot1.getLkm()); 
    assertEquals("From: Huomiot line: 126", 0, huomiot1.poistaPaivanHuomiot(3)); assertEquals("From: Huomiot line: 126", 2, huomiot1.getLkm()); 
    List<Huomio> huo = huomiot1.annaHuomio(2); 
    assertEquals("From: Huomiot line: 128", 0, huo.size()); 
    huo = huomiot1.annaHuomio(1); 
    assertEquals("From: Huomiot line: 130", sataa11, huo.get(0)); 
    assertEquals("From: Huomiot line: 131", sataa12, huo.get(1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedosto152 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedosto152() throws SailoException {    // Huomiot: 152
    Huomiot huomioita = new Huomiot(); 
    Huomio sataa2 = new Huomio(); sataa2.testiHuomio(2); 
    Huomio sataa1 = new Huomio(); sataa1.testiHuomio(1); 
    Huomio sataa21 = new Huomio(); sataa21.testiHuomio(2); 
    Huomio sataa12 = new Huomio(); sataa12.testiHuomio(1); 
    Huomio sataa22 = new Huomio(); sataa22.testiHuomio(2); 
    String tiedostoNimi = "testirekisteri"; 
    File ftied = new File(tiedostoNimi+".dat"); 
    ftied.delete(); 
    try {
    huomioita.lueTiedosto(tiedostoNimi); 
    fail("Huomiot: 164 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    huomioita.lisaa(sataa2); 
    huomioita.lisaa(sataa1); 
    huomioita.lisaa(sataa21); 
    huomioita.lisaa(sataa12); 
    huomioita.lisaa(sataa22); 
    huomioita.tallennus(); 
    huomioita = new Huomiot(); 
    huomioita.lueTiedosto(tiedostoNimi); 
    Iterator<Huomio> i = huomioita.iterator(); 
    assertEquals("From: Huomiot line: 174", sataa2.toString(), i.next().toString()); 
    assertEquals("From: Huomiot line: 175", sataa1.toString(), i.next().toString()); 
    assertEquals("From: Huomiot line: 176", sataa21.toString(), i.next().toString()); 
    assertEquals("From: Huomiot line: 177", sataa12.toString(), i.next().toString()); 
    assertEquals("From: Huomiot line: 178", sataa22.toString(), i.next().toString()); 
    assertEquals("From: Huomiot line: 179", false, i.hasNext()); 
    huomioita.lisaa(sataa22); 
    huomioita.tallennus(); 
    assertEquals("From: Huomiot line: 182", true, ftied.delete()); 
    File fback = new File(tiedostoNimi+".bak"); 
    assertEquals("From: Huomiot line: 184", true, fback.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator286 */
  @Test
  public void testIterator286() {    // Huomiot: 286
    Huomiot huomioita = new Huomiot(); 
    Huomio sataa1 = new Huomio(1); huomioita.lisaa(sataa1); 
    Huomio sataa2 = new Huomio(2); huomioita.lisaa(sataa2); 
    Huomio sataa12 = new Huomio(1); huomioita.lisaa(sataa12); 
    Huomio sataa21 = new Huomio(2); huomioita.lisaa(sataa21); 
    Huomio sataa13 = new Huomio(1); huomioita.lisaa(sataa13); 
    Iterator<Huomio> ite = huomioita.iterator(); 
    assertEquals("From: Huomiot line: 299", sataa1, ite.next()); 
    assertEquals("From: Huomiot line: 300", sataa2, ite.next()); 
    assertEquals("From: Huomiot line: 301", sataa12, ite.next()); 
    assertEquals("From: Huomiot line: 302", sataa21, ite.next()); 
    assertEquals("From: Huomiot line: 303", sataa13, ite.next()); 
    try {
    assertEquals("From: Huomiot line: 304", sataa1, ite.next()); 
    fail("Huomiot: 304 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int htunnus[] = { 1,2,1,2,1} ; 
    for (Huomio h : huomioita) {
    assertEquals("From: Huomiot line: 310", htunnus[n], h.getPaivaId()); n++; 
    }
    assertEquals("From: Huomiot line: 313", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaHuomio328 */
  @Test
  public void testAnnaHuomio328() {    // Huomiot: 328
    Huomiot huomioita = new Huomiot(); 
    Huomio sataa1 = new Huomio(1); huomioita.lisaa(sataa1); 
    Huomio sataa2 = new Huomio(2); huomioita.lisaa(sataa2); 
    Huomio sataa12 = new Huomio(1); huomioita.lisaa(sataa12); 
    Huomio sataa21 = new Huomio(2); huomioita.lisaa(sataa21); 
    Huomio sataa13 = new Huomio(1); huomioita.lisaa(sataa13); 
    Huomio sataa41 = new Huomio(4); huomioita.lisaa(sataa41); 
    List <Huomio> test; 
    test = huomioita.annaHuomio(10); 
    assertEquals("From: Huomiot line: 341", 0, test.size()); 
    test = huomioita.annaHuomio(1); 
    assertEquals("From: Huomiot line: 343", 3, test.size()); 
    assertEquals("From: Huomiot line: 344", true, test.get(0) == sataa1); 
    assertEquals("From: Huomiot line: 345", true, test.get(1) == sataa12); 
    test = huomioita.annaHuomio(4); 
    assertEquals("From: Huomiot line: 347", 1, test.size()); 
    assertEquals("From: Huomiot line: 348", true, test.get(0) == sataa41); 
  } // Generated by ComTest END
}