package rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.20 13:39:55 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class HuomioTest {



  // Generated by ComTest BEGIN
  /** testRekisterointi43 */
  @Test
  public void testRekisterointi43() {    // Huomio: 43
    Huomio huom1 = new Huomio(); 
    assertEquals("From: Huomio line: 45", 0, huom1.getHuomioId()); 
    huom1.rekisterointi(); 
    Huomio huom2 = new Huomio(); 
    huom2.rekisterointi(); 
    int n1 = huom1.getHuomioId(); 
    int n2 = huom2.getHuomioId(); 
    assertEquals("From: Huomio line: 51", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString124 */
  @Test
  public void testToString124() {    // Huomio: 124
    Huomio huomio = new Huomio(); 
    huomio.parse("   1   |  5  |   Sataa paljon  | 12:00"); 
    assertEquals("From: Huomio line: 127", "1|5|Sataa paljon|12:00", huomio.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse148 */
  @Test
  public void testParse148() {    // Huomio: 148
    Huomio huomio = new Huomio(); 
    huomio.parse("   1   |  5  |   Sataa paljon  | 12:00"); 
    assertEquals("From: Huomio line: 151", 5, huomio.getPaivaId()); 
    assertEquals("From: Huomio line: 152", "1|5|Sataa paljon|12:00", huomio.toString()); 
    huomio.rekisterointi(); 
    int n = huomio.getHuomioId(); 
    huomio.parse(""+(n+5)); 
    huomio.rekisterointi(); 
    assertEquals("From: Huomio line: 158", n+5+1, huomio.getHuomioId()); 
    assertEquals("From: Huomio line: 159", "" + (n+5+1) + "|5||", huomio.toString()); 
  } // Generated by ComTest END
}