package rekisteri.test;
// Generated by ComTest BEGIN
import rekisteri.SailoException;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.20 16:15:44 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class RekisteriTest {


  // Generated by ComTest BEGIN  // Rekisteri: 13
   private Rekisteri rekisteri; 
   private Paiva maa1; 
   private Paiva maa2; 
   private int pid1; 
   private int pid2; 
   private Huomio sataa21; 
   private Huomio sataa11; 
   private Huomio sataa22; 
   private Huomio sataa12; 
   private Huomio sataa23; 

   @SuppressWarnings("javadoc")
   public void alustaRekisteri() {
     rekisteri = new Rekisteri(); 
     maa1 = new Paiva(); maa1.paivanTiedot(); maa1.rekisteroi(); 
     maa2 = new Paiva(); maa2.paivanTiedot(); maa2.rekisteroi(); 
     pid1 = maa1.getTunnusNro(); 
     pid2 = maa2.getTunnusNro(); 
     sataa21 = new Huomio(pid2); sataa21.testiHuomio(pid2); 
     sataa11 = new Huomio(pid1); sataa11.testiHuomio(pid1); 
     sataa22 = new Huomio(pid2); sataa22.testiHuomio(pid2); 
     sataa12 = new Huomio(pid1); sataa12.testiHuomio(pid1); 
     sataa23 = new Huomio(pid2); sataa23.testiHuomio(pid2); 
     try {
     rekisteri.lisaa(maa1); 
     rekisteri.lisaa(maa2); 
     rekisteri.lisaa(sataa21); 
     rekisteri.lisaa(sataa11); 
     rekisteri.lisaa(sataa22); 
     rekisteri.lisaa(sataa12); 
     rekisteri.lisaa(sataa23); 
     } catch ( Exception e) {
        System.err.println(e.getMessage()); 
     }
   }
  // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa70 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa70() throws SailoException {    // Rekisteri: 70
    alustaRekisteri(); 
    assertEquals("From: Rekisteri line: 73", 2, rekisteri.etsi("*",0).size()); 
    rekisteri.lisaa(maa1); 
    assertEquals("From: Rekisteri line: 75", 3, rekisteri.etsi("*",0).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKorvaaLisaa98 
   * @throws SailoException when error
   */
  @Test
  public void testKorvaaLisaa98() throws SailoException {    // Rekisteri: 98
    alustaRekisteri(); 
    assertEquals("From: Rekisteri line: 101", 2, rekisteri.etsi("*",0).size()); 
    rekisteri.korvaaLisaa(maa1); 
    assertEquals("From: Rekisteri line: 103", 2, rekisteri.etsi("*",0).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista127 
   * @throws Exception when error
   */
  @Test
  public void testPoista127() throws Exception {    // Rekisteri: 127
    alustaRekisteri(); 
    assertEquals("From: Rekisteri line: 130", 2, rekisteri.etsi("*",0).size()); 
    assertEquals("From: Rekisteri line: 131", 2, rekisteri.annaHuomio(maa1).size()); 
    assertEquals("From: Rekisteri line: 132", 1, rekisteri.poista(maa1)); 
    assertEquals("From: Rekisteri line: 133", 1, rekisteri.etsi("*",0).size()); 
    assertEquals("From: Rekisteri line: 134", 0, rekisteri.annaHuomio(maa1).size()); 
    assertEquals("From: Rekisteri line: 135", 3, rekisteri.annaHuomio(maa2).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoistaHuomio149 
   * @throws Exception when error
   */
  @Test
  public void testPoistaHuomio149() throws Exception {    // Rekisteri: 149
    alustaRekisteri(); 
    assertEquals("From: Rekisteri line: 152", 2, rekisteri.annaHuomio(maa1).size()); 
    rekisteri.poistaHuomio(sataa11); 
    assertEquals("From: Rekisteri line: 154", 1, rekisteri.annaHuomio(maa1).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaHuomio176 
 * @throws SailoException */
  @Test
  public void testAnnaHuomio176() throws SailoException {    // Rekisteri: 176
    alustaRekisteri(); 
    Paiva maa3 = new Paiva(); 
    maa3.rekisteroi(); 
    rekisteri.lisaa(maa3); 
    List<Huomio> loytyneet; 
    loytyneet = rekisteri.annaHuomio(maa3); 
    assertEquals("From: Rekisteri line: 187", 0, loytyneet.size()); 
    loytyneet = rekisteri.annaHuomio(maa1); 
    assertEquals("From: Rekisteri line: 189", 2, loytyneet.size()); 
    assertEquals("From: Rekisteri line: 190", true, loytyneet.get(0) == sataa11); 
    assertEquals("From: Rekisteri line: 191", true, loytyneet.get(1) == sataa12); 
    loytyneet = rekisteri.annaHuomio(maa2); 
    assertEquals("From: Rekisteri line: 193", 3, loytyneet.size()); 
    assertEquals("From: Rekisteri line: 194", true, loytyneet.get(0) == sataa21); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi255 
   * @throws CloneNotSupportedException when error
   * @throws SailoException when error
   */
  @Test
  public void testEtsi255() throws CloneNotSupportedException, SailoException {    // Rekisteri: 255
    alustaRekisteri(); 
    Paiva maa3 = new Paiva(); maa3.rekisteroi(); 
    maa3.aseta(1,"Peruna"); 
    rekisteri.lisaa(maa3); 
    Collection<Paiva> loytyneet = rekisteri.etsi("*Peruna*", 1); 
    assertEquals("From: Rekisteri line: 262", 1, loytyneet.size()); 
    Iterator<Paiva> it = loytyneet.iterator(); 
    assertEquals("From: Rekisteri line: 264", true, it.next() == maa3); 
  } // Generated by ComTest END
}