package kanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static kanta.PvmTarkistus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.21 14:56:53 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PvmTarkistusTest {



  // Generated by ComTest BEGIN
  /** testTarkistaKello22 */
  @Test
  public void testTarkistaKello22() {    // PvmTarkistus: 22
    assertEquals("From: PvmTarkistus line: 23", "Ei ole sopiva kellonaika.", tarkistaKello("koira")); 
    assertEquals("From: PvmTarkistus line: 24", "Ei ole sopiva kellonaika.", tarkistaKello("00:1")); 
    assertEquals("From: PvmTarkistus line: 25", "Ei ole sopiva kellonaika.", tarkistaKello("56:23")); 
    assertEquals("From: PvmTarkistus line: 26", "Ei ole sopiva kellonaika.", tarkistaKello("00:70")); 
    assertEquals("From: PvmTarkistus line: 27", "Ei ole sopiva kellonaika.", tarkistaKello("21:60")); 
    assertEquals("From: PvmTarkistus line: 28", null, tarkistaKello("00:00")); 
    assertEquals("From: PvmTarkistus line: 29", null, tarkistaKello("23:59")); 
  } // Generated by ComTest END
}