package kanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.Huomio;
import kanta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.20 13:37:50 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TietueTest {



  // Generated by ComTest BEGIN
  /** testInt12 */
  @Test
  public void testInt12() {    // Tietue: 12
    Huomio huom = new Huomio(); 
    assertEquals("From: Tietue line: 15", 4, huom.getKenttia()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testInt23 */
  @Test
  public void testInt23() {    // Tietue: 23
    Huomio huom = new Huomio(); 
    assertEquals("From: Tietue line: 25", 2, huom.ensimmainenKentta()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString34 */
  @Test
  public void testString34() {    // Tietue: 34
    Huomio huom = new Huomio(); 
    assertEquals("From: Tietue line: 36", "klo", huom.getKysymys(3)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString45 */
  @Test
  public void testString45() {    // Tietue: 45
    Huomio huom = new Huomio(); 
    huom.parse("   1   |  5  |   Sataa paljon  | 12:00"); 
    assertEquals("From: Tietue line: 48", "1", huom.anna(0)); 
    assertEquals("From: Tietue line: 49", "5", huom.anna(1)); 
    assertEquals("From: Tietue line: 50", "Sataa paljon", huom.anna(2)); 
    assertEquals("From: Tietue line: 51", "12:00", huom.anna(3)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString63 */
  @Test
  public void testString63() {    // Tietue: 63
    Huomio huom = new Huomio(); 
    assertEquals("From: Tietue line: 65", null, huom.aseta(2,"Sataa vettä")); 
    assertEquals("From: Tietue line: 66", null, huom.aseta(3,"1940")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTietue76 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testTietue76() throws CloneNotSupportedException {    // Tietue: 76
    Huomio huom = new Huomio(); 
    huom.parse("   1   |  5  |   Sataa paljon  | 12:00"); 
    Object kopio = huom.clone(); 
    assertEquals("From: Tietue line: 81", huom.toString(), kopio.toString()); 
    huom.parse("   2   |  15  |   Ei sada  | 11:00"); 
    assertEquals("From: Tietue line: 83", false, kopio.toString().equals(huom.toString())); 
    assertEquals("From: Tietue line: 84", true, kopio instanceof Huomio); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString94 */
  @Test
  public void testString94() {    // Tietue: 94
    Huomio huomio = new Huomio(); 
    huomio.parse("   1   |  5  |   Sataa paljon  | 12:00"); 
    { String _l_=huomio.toString(),_r_="1\\|5\\|Sataa paljon\\|12:00"; if ( !_l_.matches(_r_) ) fail("From: Tietue line: 97" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END
}